#ifndef _SC_CONFIG_
#define _SC_CONFIG_

#define PREVIEW_WIDTH 120
#define PREVIEW_HEIGHT 80
#define PREVIEW_DESC_HEIGHT 30
#define PREVIEW_TOTAL_HEIGHT (PREVIEW_HEIGHT+PREVIEW_DESC_HEIGHT)
#define PREVIEW_BIAS 10

#define PREV_SCALE 5

#define DECORATED_BORDER 5
#define DECORATED_SBORDER (DECORATED_BORDER/2.0)


#define BUF_SIZE 100
#define MENU_GAP 2
//#define DECORATED_SBORDER 5

#define X 0
#define Y 1
#define XY 2






#endif
